### ISSUE TITLE
pytorch version for detectron2 under gsnet/reference_code/GSNet-release

### ISSUE THREAD

**Issue by YangLyu-123** [lkeab/gsnet#11]
Hello,

Firstly, thanks for the codes of your impressive research. 

I have an issue when running 
```
CUDA_VISIBLE_DEVICES=0 python3 demo/demo.py --config-file configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x_apollo.yaml \
  --input 'datasets/coco/val_apollo/' \
  --output 'medium_result_val/' \
  --opts MODEL.WEIGHTS ./output/model_final.pth
```

### The error information:

```
Traceback (most recent call last):
  File "demo/demo.py", line 11, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/Test/code/gsnet/reference_code/GSNet-release/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/Test/code/gsnet/reference_code/GSNet-release/detectron2/data/build.py", line 14, in <module>
    from detectron2.structures import BoxMode
  File "/home/Test/code/gsnet/reference_code/GSNet-release/detectron2/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou
  File "/home/Test/code/gsnet/reference_code/GSNet-release/detectron2/structures/boxes.py", line 8, in <module>
    from detectron2.layers import cat
  File "/home/Test/code/gsnet/reference_code/GSNet-release/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/Test/code/gsnet/reference_code/GSNet-release/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: /home/Test/code/gsnet/reference_code/GSNet-release/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass
```

### Env information
```
python: 3.6.2
CUDA: 10.1
pytorch: 1.5.0
ubuntu: 18.04
```

The existing solutions about this issue give me that the version of pytorch is incompatible with detectron2. 

### What I tried
- Remove the detectron2 and detectron2.egg-info you provided and reinstall detectron2 via
```
python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html
```
By doing this I got:
```
Traceback (most recent call last):
  File "demo/demo.py", line 73, in <module>
    cfg = setup_cfg(args)
  File "demo/demo.py", line 28, in setup_cfg
    cfg.MODEL.FCOS.INFERENCE_TH = args.confidence_threshold
  File "/home/Test/anaconda3/envs/gsnet/lib/python3.6/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: FCOS
```

It looks like that the the version of detectron2 provided in GSNet-release is different from that from https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html

So could you please give some hints about the version of pytorch used for the detectron2 provided in GSNet-release? 

Many thanks in advance.

**Comment by lkeab** [comment]
The FCOS error is becuase this [line](https://github.com/lkeab/gsnet/blob/master/reference_code/GSNet-release/detectron2/config/defaults.py#L402) not being excuted.

**Comment by lkeab** [comment]
How about trying pytorch 1.3 or 1.4 and using the [setup.py](https://github.com/lkeab/gsnet/blob/master/reference_code/GSNet-release/setup.py) here, and using "python3 setup.py build develop" to install.

**Comment by YangLyu-123** [comment]
> The FCOS error is becuase this [line](https://github.com/lkeab/gsnet/blob/master/reference_code/GSNet-release/detectron2/config/defaults.py#L402) not being excuted.

Yes, in https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.5/index.html each version for py36, `FCOS` is removed.

**Comment by YangLyu-123** [comment]
> How about trying pytorch 1.3 or 1.4 and using the [setup.py](https://github.com/lkeab/gsnet/blob/master/reference_code/GSNet-release/setup.py) here, and using "python3 setup.py build develop" to install.

Thanks for your reply :) Downgrading pytorch from 1.5 to 1.4 works for me about the following error!
```
ImportError: /home/Test/code/gsnet/reference_code/GSNet-release/detectron2/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass
```

**Comment by meassinal** [comment]
Hi,
I have the same problem with `FCOS`, and after downgrading to pytorch `1.4` I have the following error:
```
Traceback (most recent call last):
  File "demo/demo.py", line 11, in <module>
    from detectron2.data.detection_utils import read_image
  File "/home/azureuser/.virtualenvs/py36/lib/python3.6/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/azureuser/.virtualenvs/py36/lib/python3.6/site-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/home/azureuser/.virtualenvs/py36/lib/python3.6/site-packages/detectron2/structures/__init__.py", line 6, in <module>
    from .keypoints import Keypoints, heatmaps_to_keypoints
  File "/home/azureuser/.virtualenvs/py36/lib/python3.6/site-packages/detectron2/structures/keypoints.py", line 6, in <module>
    from detectron2.layers import interpolate
  File "/home/azureuser/.virtualenvs/py36/lib/python3.6/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/azureuser/.virtualenvs/py36/lib/python3.6/site-packages/detectron2/layers/deform_conv.py", line 10, in <module>
    from detectron2 import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory
```

I really appreciate if you can help point out how I should do to make it work successfully. Thanks in advance.

**Comment by lkeab** [comment]
Hi, you could refer to the solutions [here](https://github.com/pytorch/pytorch/issues/38090).

**Comment by meassinal** [comment]
> Hi, you could refer to the solutions [here](https://github.com/pytorch/pytorch/issues/38090).

After checking, `libtorch_cpu.so` does exists in `pytorch 1.5` but not in version `1.4`. However, there is an issue of `FCOS` in version `1.5` so that I could not run the demo successfully. 

What else could you advice? Thanks in advance for your answer :)
