### ISSUE TITLE
Demo failed because of FCOS

### ISSUE THREAD

**Issue by meassinal** [lkeab/gsnet#14]
First of all, I'd like to thank you for your code.

I followed instructions in README, but I have a problem with the demo caused by an error below:

```
[10/29 03:45:35 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x_apollo.yaml', input=['datasets/coco/val_apollo/'], opts=['MODEL.WEIGHTS', './output/model_final.pth'], output='medium_result_val/', video_input=None, webcam=False)
Traceback (most recent call last):
  File "demo/demo.py", line 73, in <module>
    cfg = setup_cfg(args)
  File "demo/demo.py", line 28, in setup_cfg
    cfg.MODEL.FCOS.INFERENCE_TH = args.confidence_threshold
  File "/home/azureuser/.virtualenvs/py36/lib/python3.6/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: FCOS
```
Could you help point out what I should do to make it run successfully? Thanks in advance.

**Comment by lkeab** [comment]
Hi, sorry for the late reply. please refer to the discussion [here](https://github.com/lkeab/gsnet/issues/11).
