### ISSUE TITLE
CUDA11.1+Torch 1.8 

### ISSUE THREAD

**Issue by yuhanyuhang** [lkeab/gsnet#7]
I have successfully built Detectron2 under this environment. But when i build SoftRas，i meet this problem. Can you give me some advice? Thanks so much.

1 error detected in the compilation of "D:/ApolloCar3D/各种pip包/SoftRas-master/soft_renderer/cuda/soft_rasterize_cuda_kernel.cu".
soft_rasterize_cuda_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 690, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\One\anaconda3\envs\detectron2\lib\site-packages\torch\utils\cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by lkeab** [comment]
It's great that I have seen this problem has been solved in [here](https://github.com/ShichenLiu/SoftRas/issues/84#issuecomment-858640024).
